### ISSUE TITLE
Releases for Watch Notifications 

### ISSUE THREAD

**Issue by erancihan** [uber-go/guide#154]
While I'm sure it might add an extra step, another thing to do for PRs, I think having "Releases" would help people that are not actively participating, but want to learn about changes/updates to the guide and get notified.

Thank you so much for this project!

**Comment by abhinav** [comment]
Sounds good. We can experiment with tagging a release when we make significant changes or additions.

If that ends up being too messy, an alternative can be a tracking issue where we post updates,
so watchers can follow that issue and nothing else.

**Comment by erancihan** [comment]
Closing because release tagging is being made.

Thank you!
