### ISSUE TITLE
Proposal: Add Type Parameters ( Generics )

### ISSUE THREAD

**Issue by Skarlso** [uber-go/guide#155]
Hello.

It would be nice now that [Type Parameters](https://go.googlesource.com/proposal/+/HEAD/design/43651-type-parameters.md) is generally available, to add some guidelines on them.

I don't have any specifics yet, but I wanted to create this placeholder issue for it.

**Comment by sywhang** [comment]
Hey @Skarlso, thanks for posting this. We actually have a Discussion item tracking this: https://github.com/uber-go/guide/discussions/139, so I'll close this as a duplicate. We're discussing this internally but if you have any suggestions feel free to post it in the Discussions thread I linked!

**Comment by Skarlso** [comment]
Cool! Thanks @sywhang!
