### ISSUE TITLE
Misleading formulation in "Receivers and Interfaces"

### ISSUE THREAD

**Issue by fbilhaut** [uber-go/guide#163]
In `guide/style.md`:

The word **"only"** in the following comment is misleading and should be removed:

```
// You can only call Read using a value
```

In my understanding, this would mean that calling `Read` using a pointer is not possible, which is the opposite of the actual point of this section. 

See the french translation, for example, which reformulated it correctly.

**Comment by abhinav** [comment]
I agree that this could be reworded to be better.

I think that example hides the subtlety that we cannot take a pointer of a value stored in a map,
which makes it impossible to call Write on that instance.
The "only" refers to the methods available on the object.
