### ISSUE TITLE
Clarify embed guidance to address exported type APIs

### ISSUE THREAD

**Issue by mway** [uber-go/guide#23]
Expanding on #21, we should make a distinction for exported and unexported types, and call out advice to avoid bleeding implementation details through APIs when embedding.

cc @abhinav @prashantv

**Comment by prashantv** [comment]
We do [call this out](https://github.com/uber-go/guide/blob/master/style.md#zero-value-mutexes-are-valid)
> For exported types, use a private lock.

Maybe we should make this more explicitly since the current guidance is below an example

**Comment by abhinav** [comment]
I think outside of the mutex discussion, @mway is suggesting that we advise
against embedding in general when doing so would leak implementation details.

**Comment by prashantv** [comment]
You're right, that makes sense. @mway Do you want to add a recommendation for that?

**Comment by mway** [comment]
Yeah, I'll put something up for that tonight or tomorrow.
