### ISSUE TITLE
Consider adding "var _ Interface = (*Type)(nil)" to the list of recommendations

### ISSUE THREAD

**Issue by shyiko** [uber-go/guide#25]
This is a relatively common Go idiom equivalent to Java's "implements", Rust's "impl ... for", etc.
It
- asserts that types implement expected set of interfaces (declaration of intent), guarding against breakage caused by method signature changes
- improves readability by making things explicit & acting as an additional form of documentation
- helps with code navigation/generation (e.g. in GoLand Alt+Insert on `(*Type)(nil)` gives `Implement Missing Methods` option).

<table>
<thead><tr><th>Bad</th><th>Good</th></tr></thead>
<tbody>
<tr><td>

```go
type A struct{}

func New() A {
	return A{}
}

func (a A) Read(p []byte) (n int, err error) {
	panic("implement me")
}

func (a A) Close() error {
	panic("implement me")
}
```

</td><td>

```go
type A struct{}

var _ io.ReadCloser = (*A)(nil)

func New() A {
	return A{}
}

func (a A) Read(p []byte) (n int, err error) {
	panic("implement me")
}

func (a A) Close() error {
	panic("implement me")
}
```

</td></tr>
</tbody></table>

I'd be happy to submit a PR.

**Comment by prashantv** [comment]
+1, if a type is expected to satisfy an interface, and we don't already verify this, then the `var _ <interface> = <type instantiation>` makes sense.

An alternate is to make the `New` function return the interface type directly, in which case the variable declaration is unnecessary.

**Comment by abhinav** [comment]
+1 on the `var _` recommendation.

Having `New` return the interface would go against the "return structs" adage,
so I'd like to avoid that for now.

**Comment by prashantv** [comment]
Good point.

There are cases when the compiler will already have the check, e.g., a custom implementation of [`net.Listener`](https://golang.org/pkg/net/#Listener) returns a `net.Conn` from `Accept`, so it's technically unnecessary to add another check if a custom connection type is returned.

That said, it seems simpler to just add the recommendation, and not worry about the corner cases.

**Comment by abhinav** [comment]
Landed

**Comment by PeterlitsZo** [comment]
If the interface is defined in a package `foo`, and I try to let struct `BarStruct` implement it in another package `bar`.

Now I invoke `NewBarStruct` in package `foo`, so now:

- the package `foo` depends on package `bar` (to invoke `NewBarStruct` function),
- the package `bar` depends on package `foo` (to use statement `var _ (foo.FooInterface) = BarStruct{}`)

Now it will raise an error, right?

**Comment by PeterlitsZo** [comment]
```go
// foo/main.go
package foo

import "foobar.com/m/bar"

type Itfc interface {
	X() int
}

func main() {
	stct := bar.NewStct()
}


// bar/main.go
package bar

import "foobar.com/m/foo"

type Stct struct {
	x int
}

func (s Stct) X() int {
	return s.x
}

var _ (foo.Itfc) = Stct{}

func NewStct() Stct {
	return Stct{}
}
```
