### ISSUE TITLE
Is this better "Functional Options" ?

### ISSUE THREAD

**Issue by aQuaYi** [uber-go/guide#33]
Go has support for first class functions.

[Run at Go Playground](https://play.golang.org/p/JlKmxP6b2iM)

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	addr := "127.0.0.1"
	newTimeout := 10 * time.Second
	// Options must be provided only if needed.
	Connect(addr)
	Connect(addr, WithTimeout(newTimeout))
	Connect(addr, WithCaching(false))
	Connect(
		addr,
		WithCaching(false),
		WithTimeout(newTimeout),
	)
}

// Options is DB's options
type Options struct {
	timeout time.Duration
	caching bool
}

// ApplyOption overrides behavior of Connect.
type ApplyOption func(*Options)

// Option overrides behavior of Connect.
// type Option interface {
// 	apply(*Options)
// }

// type optionFunc func(*Options)

// func (f optionFunc) apply(o *Options) {
// f(o)
// }

// WithTimeout if you need
func WithTimeout(t time.Duration) ApplyOption {
	return func(o *Options) {
		o.timeout = t
		fmt.Printf("With Timeout: %s\n", t)
	}
}

// WithCaching if you need
func WithCaching(cache bool) ApplyOption {
	return func(o *Options) {
		o.caching = cache
		fmt.Printf("With Caching: %t\n", cache)
	}
}

const (
	defaultTimeout = time.Second
	defaultCaching = true
)

// Connect creates a connection.
func Connect(
	addr string,
	opts ...ApplyOption,
) (*Options, error) {
	fmt.Println("---== new Connect ==---")
	options := Options{
		timeout: defaultTimeout,
		caching: defaultCaching,
	}

	for _, apply := range opts {
		apply(&options)
	}

	return &options, nil
}
```

**Comment by TonyPythoneer** [comment]
What's different between yours and doc?

**Comment by aQuaYi** [comment]
> What's different between yours and doc?
> 
> A good engineer should provide example and explanation to prove it better.
> 
> I haven't seen any explanation.

You are right.

In doc, `Option` is an interface. You have to create `optionFunc` to implement `Option` Interface. I comment them in my code.
In my code, `ApplyFunc` is a fuction variable, do the same work as `Option` in doc, but cleaner.

**Comment by prashantv** [comment]
The comparison is between:
```go
type options struct { .. }

type Option interface {
  apply(*options)
}
```

and 
```go
type Options struct { ... }

type Option func(*Options)
```

The biggest difference is the API surface. In the first option, we've only added a single exported identifier, `Option`, and the implementation of how options work is completely hidden from external users (and API package documentation).

In the second case, there are 2 exported symbols. While it's possible to unexport `Options` in the second example, the API documentation would still show the underlying type of `Option` as `func(*options)`, which leaks the unexported types in the documentation which we avoid.

**Comment by aQuaYi** [comment]
@prashantv thanks a lot.
