### ISSUE TITLE
Avoid string-to-byte conversion -> bytes.Repeat

### ISSUE THREAD

**Issue by alexisvisco** [uber-go/guide#40]
In the case of:
```go
data := []byte("Hello world")
for i := 0; i < b.N; i++ {
  w.Write(data)
}
```

Why should you not using [bytes.Repeat](https://golang.org/src/bytes/bytes.go?s=12715:12754#L480) instead of this snippet of code ?

The intent of this code is exactly the same as bytes.Repeat without the benefits.

**Comment by alexisvisco** [comment]
```go
func Benchmark_Repeat(b *testing.B) {
	b.Run("no-repeat", func(n *testing.B) {
		w := bytes.NewBuffer([]byte{})
		data := []byte("Hello world")
		for i := 0; i < n.N; i++ {
			w.Write(data)
		}
	})
	b.Run("repeat", func(n *testing.B) {
		w := bytes.NewBuffer([]byte{})
		data := []byte("Hello world")
		w.Write(bytes.Repeat(data, n.N))
	})
}```

Result in:

```
Benchmark_Repeat/no-repeat-4         	50000000	        43.7 ns/op
Benchmark_Repeat/repeat-4            	100000000	        18.3 ns/op
```

**Comment by abhinav** [comment]
Hey @alexisvisco, the intent of that sample is to demonstrate the cost of
string-to-byte conversion. It's not meant to be the most optimal way of
writing `"hello world" * b.N` to a stream.

For benchmarking, the two samples need to be close-to-equivalent, differing
only in the behavior being measured. In this case, that means that the number
of calls to `w.Write`, and the bytes passed to `w.Write` must be the same each
call.

`bytes.Repeat` will lead to an imbalanced benchmark: one case will make `b.N`
calls to `w.Write` with `len("hello world")` bytes, while the other will make
a single call to `w.Write` with `len("hello world") * b.N` bytes.

Closing the issue as this answers the question. Feel free to re-open if you
disagree.

Thanks!
