### ISSUE TITLE
What is the preferred way to instantiate an empty map?

### ISSUE THREAD

**Issue by wxdao** [uber-go/guide#44]
a nil slice is a valid slice and there's no problem doing `append(nilSlice, elem)`. However, a nil map isn't and it has to be instantiated before further use.

How do you recommend to instantiate an empty map? `m := map[type]type{}`  or  `m := make(map[type]type)` or something else?

**Comment by mway** [comment]
Both are valid and used depending on the surrounding context. For empty maps, we prefer `make(map[T1]T2)`. Some notes about initializing maps in general:

## With `make()`
```go
m := make(map[T1]T2)
```
Where reasonable, we prefer to initialize a map with `make()` versus map literals as the intent is generally easier to understand: `map[T1]T2` (declaration) and `map[T1]T2{}` (initialization) are visually similar but functionally different. For example: 

```go
// These two declarations have a lower Levenshtein distance.
var (
  m1 = map[T1]T2{}
  m2 map[T1]T2
)
```
versus
```go
// These two declarations have a greater Levenshtein distance.
var (
  m1 = make(map[T1]T2)
  m2 map[T1]T2
)
```

Additionally, given that the signature for `make()` with a map is `make(map[T1]T2[, capacity_hint])`, refactors that add/remove the capacity hint are simpler:

```diff
diff --git a/tmp.go b/tmp.go
index 8aa33cc41..e07a845d9 100644
--- a/tmp.go
+++ b/tmp.go
@@ -1 +1 @@
-m := make(map[T1]T2)
+m := make(map[T1]T2, hint)
```
versus
```diff
diff --git a/tmp.go b/tmp.go
index e014e4f64..e07a845d9 100644
--- a/tmp.go
+++ b/tmp.go
@@ -1 +1 @@
-m := map[T1]T2{}
+m := make(map[T1]T2, hint)
```

Some basic rules of thumb for using `make(map[T1]T2)`:
- when an empty map is being initialized
- when map elements must be added programmatically, versus as part of the map literal
- when it is optimal to pre-allocate storage (based on an understanding of Go's internal hashmap implementation, see [`makemap()` in runtime/map.go](https://github.com/golang/go/blob/master/src/runtime/map.go#L303-L336))
- when the rest of the codebase uses `make(map[T1]T2)`

## With map literals
```go
m := map[T1]T2{}
```

Initialization with a map literal is preferable in cases in which:
- a static set of keys are being added to a new map
- when the map can reasonably be used like an rvalue (in C++ parlance)
- when the rest of the codebase uses `map[T1]T2{}`

---

There are more nuances than this, obviously. :) Not sure if you were suggesting that this be added to the guide, but I'm not sure that it'd be tremendously valuable to attempt to codify enough nuances/contexts for map creation to add it (aside from the universal recommendation of "be consistent").

@abhinav @prashantv thoughts?

**Comment by abhinav** [comment]
@mway I agree strongly with your rationale for the two choices. We've
encouraged a similar pattern during code reviews but did not have a chance to
articulate the full reasoning until now.

I don't think we'd need to account for all nuances. A general recommendation
of `make` (with or without size hint) for empty or dynamically sized, and
literal for non-empty with fixed size should suffice. Plus a version of the
rationale above.

Perhaps we should also just add a separate thing at the top with the universal
"be consistent" recommendation.
