### ISSUE TITLE
Guideline: One log.Fatal per application

### ISSUE THREAD

**Issue by abhinav** [uber-go/guide#66]
This is to track adding a guideline around use of log.Fatal. Our
recommendation in code reviews has been to have exactly one log.Fatal per
application: in the main. Everything else should return an error.

**Comment by mway** [comment]
Observationally, this seems to be used as a panic-that-isn't-called-panic where either (a) it's unknown how to handle that error at the callsite or (b) errors aren't being propagated. It's probably worth adding explicit guidance around error handling/plumbing (#67).
