### ISSUE TITLE
Error Types, Error Wrapping: Go1.13 Errors 

### ISSUE THREAD

**Issue by ZYunH** [uber-go/guide#69]
Maybe we could follow the new features introduced in Go1.13, see https://blog.golang.org/go1.13-errors
For instance, we can use errors.Is, instead of expose some functions like `IsFooError`. The former is more readable and concise.

**Comment by prashantv** [comment]
Yes, we need to extend guidance to use the new error wrapping/unwrapping features of Go 1.13. This is currently tracked in #8.
