### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by Megidd** [uber-go/guide#88]
In the section [Avoid Naked Parameters](https://github.com/uber-go/guide/blob/master/style.md#avoid-naked-parameters), this example:

```go
type Status int

const (
  StatusReady = iota + 1
  StatusDone
  // Maybe we will have a StatusInProgress in the future.
)
```

Shouldn't it be? :

```go
type Status int

const (
  StatusReady Status = iota + 1 // Notice `Status` type here
  StatusDone
  // Maybe we will have a StatusInProgress in the future.
)
```

**Comment by mway** [comment]
Yes, that's correct! Thanks for pointing this out. Feel free to open a PR fixing this - otherwise, we'll fix it in the next day or two.
